In [1]:
# Importing required libraries
import pandas as pd
import numpy as np

In [15]:
# Loading the dataset
df=pd.read_csv("emp_rec.csv")
df.shape

(30000, 8)

In [3]:
# Dataset 
df.head()

,Employee_ID,Employee_Name,Age,Country,Department,Position,Salary,Joining_Date
0,1,Daniel Taylor,25,UK,HR,Analyst,142278.32,2023-06-04
1,2,Ethan Brown,44,India,Marketing,Executive,98549.20,2018-01-13
2,3,Sophia Martinez,51,Japan,Finance,Developer,85565.84,2015-04-30
3,4,Ethan Martinez,47,Germany,Support,Analyst,34513.67,2015-06-17
4,5,Mia Brown,32,Australia,Support,Consultant,45339.72,2019-02-22

In [4]:
# information of database
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Employee_ID    30000 non-null  int64
 1   Employee_Name  30000 non-null  object
 2   Age            30000 non-null  int64
 3   Country        30000 non-null  object
 4   Department     30000 non-null  object
 5   Position       30000 non-null  object
 6   Salary         30000 non-null  float64
 7   Joining_Date   30000 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 1.8+ MB

In [5]:
df.describe(include='all')

,Employee_ID,Employee_Name,Age,Country,Department,Position,Salary,Joining_Date
count,30000.000000,30000,30000.000000,30000,30000,30000,30000.000000,30000
unique,NaN,100,NaN,10,6,6,NaN,3649
top,NaN,Lily Martinez,NaN,Germany,Engineering,Executive,NaN,2021-12-31
freq,NaN,338,NaN,3090,5070,5124,NaN,25
mean,15000.500000,NaN,40.978067,NaN,NaN,NaN,89826.142610,NaN
std,8660.398374,NaN,11.234432,NaN,NaN,NaN,34625.270533,NaN
min,1.000000,NaN,22.000000,NaN,NaN,NaN,30004.780000,NaN
25%,7500.750000,NaN,31.000000,NaN,NaN,NaN,59546.715000,NaN
50%,15000.500000,NaN,41.000000,NaN,NaN,NaN,89544.810000,NaN
75%,22500.250000,NaN,51.000000,NaN,NaN,NaN,119836.545000,NaN
max,30000.000000,NaN,60.000000,NaN,NaN,NaN,149996.390000,NaN

In [6]:
# Missing Values
df.isnull().sum()

Employee_ID      0
Employee_Name    0
Age              0
Country          0
Department       0
Position         0
Salary           0
Joining_Date     0
dtype: int64

In [7]:
# Checking for duplicates
df.duplicated().sum()

np.int64(0)

In [8]:
# Data type transformation
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')

In [9]:
# Outliers using IQR
Q1 = df['Salary'].quantile(0.25)
Q3 = df['Salary'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['Salary'] < lower) | (df['Salary'] > upper)]
print([lower,upper])
print(outliers)

[np.float64(-30888.03), np.float64(210271.28999999998)]
Empty DataFrame
Columns: [Employee_ID, Employee_Name, Age, Country, Department, Position, Salary, Joining_Date]
Index: []

In [10]:
# Min-Max Normalization
df['Salary_Normalized'] = (
 (df['Salary'] - df['Salary'].min()) /
 (df['Salary'].max() - df['Salary'].min())
) 
df.head()

,Employee_ID,Employee_Name,Age,Country,Department,Position,Salary,Joining_Date,Salary_Normalized
0,1,Daniel Taylor,25,UK,HR,Analyst,142278.32,2023-06-04,0.935678
1,2,Ethan Brown,44,India,Marketing,Executive,98549.20,2018-01-13,0.571243
2,3,Sophia Martinez,51,Japan,Finance,Developer,85565.84,2015-04-30,0.463041
3,4,Ethan Martinez,47,Germany,Support,Analyst,34513.67,2015-06-17,0.037577
4,5,Mia Brown,32,Australia,Support,Consultant,45339.72,2019-02-22,0.127800

In [11]:
# Z-Score for Salary,Age
df['Salary_z'] = (df['Salary'] - df['Salary'].mean()) / df['Salary'].std()
df['Age_z'] = (df['Age'] - df['Age'].mean()) / df['Age'].std()
df.head()

,Employee_ID,Employee_Name,Age,Country,Department,Position,Salary,Joining_Date,Salary_Normalized,Salary_z,Age_z
0,1,Daniel Taylor,25,UK,HR,Analyst,142278.32,2023-06-04,0.935678,1.514852,-1.422241
1,2,Ethan Brown,44,India,Marketing,Executive,98549.20,2018-01-13,0.571243,0.251927,0.268989
2,3,Sophia Martinez,51,Japan,Finance,Developer,85565.84,2015-04-30,0.463041,-0.123040,0.892073
3,4,Ethan Martinez,47,Germany,Support,Analyst,34513.67,2015-06-17,0.037577,-1.597460,0.536025
4,5,Mia Brown,32,Australia,Support,Consultant,45339.72,2019-02-22,0.127800,-1.284796,-0.799156

In [12]:
# Log Transformation
df['Salary_log'] = np.log(df['Salary'] + 1)
df.head()

,Employee_ID,Employee_Name,Age,Country,Department,Position,Salary,Joining_Date,Salary_Normalized,Salary_z,Age_z,Salary_log
0,1,Daniel Taylor,25,UK,HR,Analyst,142278.32,2023-06-04,0.935678,1.514852,-1.422241,11.865547
1,2,Ethan Brown,44,India,Marketing,Executive,98549.20,2018-01-13,0.571243,0.251927,0.268989,11.498321
2,3,Sophia Martinez,51,Japan,Finance,Developer,85565.84,2015-04-30,0.463041,-0.123040,0.892073,11.357053
3,4,Ethan Martinez,47,Germany,Support,Analyst,34513.67,2015-06-17,0.037577,-1.597460,0.536025,10.449140
4,5,Mia Brown,32,Australia,Support,Consultant,45339.72,2019-02-22,0.127800,-1.284796,-0.799156,10.721961

In [13]:
# Encoding
df['Country_code'] = df['Country'].astype('category').cat.codes
df.head()

,Employee_ID,Employee_Name,Age,Country,Department,Position,Salary,Joining_Date,Salary_Normalized,Salary_z,Age_z,Salary_log,Country_code
0,1,Daniel Taylor,25,UK,HR,Analyst,142278.32,2023-06-04,0.935678,1.514852,-1.422241,11.865547,8
1,2,Ethan Brown,44,India,Marketing,Executive,98549.20,2018-01-13,0.571243,0.251927,0.268989,11.498321,5
2,3,Sophia Martinez,51,Japan,Finance,Developer,85565.84,2015-04-30,0.463041,-0.123040,0.892073,11.357053,6
3,4,Ethan Martinez,47,Germany,Support,Analyst,34513.67,2015-06-17,0.037577,-1.597460,0.536025,10.449140,4
4,5,Mia Brown,32,Australia,Support,Consultant,45339.72,2019-02-22,0.127800,-1.284796,-0.799156,10.721961,0