In [1]:
import pandas as pd
import numpy as np

In [25]:
data = {
    "Student_ID": ["S01","S02","S03","S04","S05","S06","S07","S08"],
    "Age": [20,21,22,np.nan,20,23,21,22],
    "Marks": [85,np.nan,92,45,300,78,65,np.nan],
    "Attendance": [90,75,95,40,85,np.nan,70,60],
    "Gender": ["Male","Female","Male","Female","Male","Female","Male","Female"],
    "Department": ["CS","IT","CS","IT","CS","CS","IT","CS"]
}
df = pd.DataFrame(data)
df

  Student_ID   Age  Marks  Attendance  Gender Department
0        S01  20.0   85.0        90.0    Male         CS
1        S02  21.0    NaN        75.0  Female         IT
2        S03  22.0   92.0        95.0    Male         CS
3        S04   NaN   45.0        40.0  Female         IT
4        S05  20.0  300.0        85.0    Male         CS
5        S06  23.0   78.0         NaN  Female         CS
6        S07  21.0   65.0        70.0    Male         IT
7        S08  22.0    NaN        60.0  Female         CS

In [26]:
# Q1
print("Shape:", df.shape)
print("\nData Types:\n", df.dtypes)
df

Shape: (8, 6)

Data Types:
 Student_ID     object
Age           float64
Marks         float64
Attendance    float64
Gender         object
Department     object
dtype: object

  Student_ID   Age  Marks  Attendance  Gender Department
0        S01  20.0   85.0        90.0    Male         CS
1        S02  21.0    NaN        75.0  Female         IT
2        S03  22.0   92.0        95.0    Male         CS
3        S04   NaN   45.0        40.0  Female         IT
4        S05  20.0  300.0        85.0    Male         CS
5        S06  23.0   78.0         NaN  Female         CS
6        S07  21.0   65.0        70.0    Male         IT
7        S08  22.0    NaN        60.0  Female         CS

In [27]:
# Q2
print("Missing values:\n", df.isnull().sum())
print("\nDuplicate rows:", df.duplicated().sum())

Missing values:
 Student_ID    0
Age           1
Marks         2
Attendance    1
Gender        0
Department    0
dtype: int64

Duplicate rows: 0

In [28]:
print("Column wise missing:\n", df.isnull().sum())
print("Row wise missing:\n", df.isnull().sum(axis=1))

Column wise missing:
 Student_ID    0
Age           1
Marks         2
Attendance    1
Gender        0
Department    0
dtype: int64
Row wise missing:
 0    0
1    1
2    0
3    1
4    0
5    1
6    0
7    1
dtype: int64

In [29]:
df['Age']=df["Age"].fillna(df["Age"].mean())
df["Marks"]=df["Marks"].fillna(df["Marks"].median())
df["Attendance"]=df["Attendance"].fillna(method="ffill")

df

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19352\1699760087.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Attendance"]=df["Attendance"].fillna(method="ffill")

  Student_ID        Age  Marks  Attendance  Gender Department
0        S01  20.000000   85.0        90.0    Male         CS
1        S02  21.000000   81.5        75.0  Female         IT
2        S03  22.000000   92.0        95.0    Male         CS
3        S04  21.285714   45.0        40.0  Female         IT
4        S05  20.000000  300.0        85.0    Male         CS
5        S06  23.000000   78.0        85.0  Female         CS
6        S07  21.000000   65.0        70.0    Male         IT
7        S08  22.000000   81.5        60.0  Female         CS

In [11]:
df.dropna(inplace=True)
df

  Student_ID        Age  Marks  Attendance  Gender Department
0        S01  20.000000   85.0        90.0    Male         CS
1        S02  21.000000   81.5        75.0  Female         IT
2        S03  22.000000   92.0        95.0    Male         CS
3        S04  21.285714   45.0        40.0  Female         IT
4        S05  20.000000  300.0        85.0    Male         CS
5        S06  23.000000   78.0        85.0  Female         CS
6        S07  21.000000   65.0        70.0    Male         IT
7        S08  22.000000   81.5        60.0  Female         CS

In [12]:
Q1 = df["Marks"].quantile(0.25)
Q3 = df["Marks"].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df["Marks"] < lower) | (df["Marks"] > upper)]
print("Outliers:\n", outliers)

Outliers:
   Student_ID        Age  Marks  Attendance  Gender Department
3        S04  21.285714   45.0        40.0  Female         IT
4        S05  20.000000  300.0        85.0    Male         CS

In [13]:
df["Marks"] = np.where(df["Marks"] > upper, upper,
                np.where(df["Marks"] < lower, lower, df["Marks"]))
df

  Student_ID        Age   Marks  Attendance  Gender Department
0        S01  20.000000   85.00        90.0    Male         CS
1        S02  21.000000   81.50        75.0  Female         IT
2        S03  22.000000   92.00        95.0    Male         CS
3        S04  21.285714   56.75        40.0  Female         IT
4        S05  20.000000  104.75        85.0    Male         CS
5        S06  23.000000   78.00        85.0  Female         CS
6        S07  21.000000   65.00        70.0    Male         IT
7        S08  22.000000   81.50        60.0  Female         CS

In [14]:
df["Marks_MA"] = df["Marks"].rolling(window=2, min_periods=1).mean()
df

  Student_ID        Age   Marks  Attendance  Gender Department  Marks_MA
0        S01  20.000000   85.00        90.0    Male         CS    85.000
1        S02  21.000000   81.50        75.0  Female         IT    83.250
2        S03  22.000000   92.00        95.0    Male         CS    86.750
3        S04  21.285714   56.75        40.0  Female         IT    74.375
4        S05  20.000000  104.75        85.0    Male         CS    80.750
5        S06  23.000000   78.00        85.0  Female         CS    91.375
6        S07  21.000000   65.00        70.0    Male         IT    71.500
7        S08  22.000000   81.50        60.0  Female         CS    73.250

In [15]:
df["Marks_Log"] = np.log(df["Marks"])
df["Attendance_Sqrt"] = np.sqrt(df["Attendance"])
df

,Student_ID,Age,Marks,Attendance,Gender,Department,Marks_MA,Marks_Log,Attendance_Sqrt
0,S01,20.000000,85.00,90.0,Male,CS,85.000,4.442651,9.486833
1,S02,21.000000,81.50,75.0,Female,IT,83.250,4.400603,8.660254
2,S03,22.000000,92.00,95.0,Male,CS,86.750,4.521789,9.746794
3,S04,21.285714,56.75,40.0,Female,IT,74.375,4.038656,6.324555
4,S05,20.000000,104.75,85.0,Male,CS,80.750,4.651577,9.219544
5,S06,23.000000,78.00,85.0,Female,CS,91.375,4.356709,9.219544
6,S07,21.000000,65.00,70.0,Male,IT,71.500,4.174387,8.366600
7,S08,22.000000,81.50,60.0,Female,CS,73.250,4.400603,7.745967

In [17]:
df = pd.get_dummies(df, columns=["Gender"])
df

,Student_ID,Age,Marks,Attendance,Department,Marks_MA,Marks_Log,Attendance_Sqrt,Gender_Female,Gender_Male
0,S01,20.000000,85.00,90.0,CS,85.000,4.442651,9.486833,False,True
1,S02,21.000000,81.50,75.0,IT,83.250,4.400603,8.660254,True,False
2,S03,22.000000,92.00,95.0,CS,86.750,4.521789,9.746794,False,True
3,S04,21.285714,56.75,40.0,IT,74.375,4.038656,6.324555,True,False
4,S05,20.000000,104.75,85.0,CS,80.750,4.651577,9.219544,False,True
5,S06,23.000000,78.00,85.0,CS,91.375,4.356709,9.219544,True,False
6,S07,21.000000,65.00,70.0,IT,71.500,4.174387,8.366600,False,True
7,S08,22.000000,81.50,60.0,CS,73.250,4.400603,7.745967,True,False

In [18]:
df["Marks_MinMax"] = (df["Marks"] - df["Marks"].min()) / (df["Marks"].max() - df["Marks"].min())
df

,Student_ID,Age,Marks,Attendance,Department,Marks_MA,Marks_Log,Attendance_Sqrt,Gender_Female,Gender_Male,Marks_MinMax
0,S01,20.000000,85.00,90.0,CS,85.000,4.442651,9.486833,False,True,0.588542
1,S02,21.000000,81.50,75.0,IT,83.250,4.400603,8.660254,True,False,0.515625
2,S03,22.000000,92.00,95.0,CS,86.750,4.521789,9.746794,False,True,0.734375
3,S04,21.285714,56.75,40.0,IT,74.375,4.038656,6.324555,True,False,0.000000
4,S05,20.000000,104.75,85.0,CS,80.750,4.651577,9.219544,False,True,1.000000
5,S06,23.000000,78.00,85.0,CS,91.375,4.356709,9.219544,True,False,0.442708
6,S07,21.000000,65.00,70.0,IT,71.500,4.174387,8.366600,False,True,0.171875
7,S08,22.000000,81.50,60.0,CS,73.250,4.400603,7.745967,True,False,0.515625

In [19]:
df["Age_Z"] = (df["Age"] - df["Age"].mean()) / df["Age"].std()
df

,Student_ID,Age,Marks,Attendance,Department,Marks_MA,Marks_Log,Attendance_Sqrt,Gender_Female,Gender_Male,Marks_MinMax,Age_Z
0,S01,20.000000,85.00,90.0,CS,85.000,4.442651,9.486833,False,True,0.588542,-1.248075
1,S02,21.000000,81.50,75.0,IT,83.250,4.400603,8.660254,True,False,0.515625,-0.277350
2,S03,22.000000,92.00,95.0,CS,86.750,4.521789,9.746794,False,True,0.734375,0.693375
3,S04,21.285714,56.75,40.0,IT,74.375,4.038656,6.324555,True,False,0.000000,0.000000
4,S05,20.000000,104.75,85.0,CS,80.750,4.651577,9.219544,False,True,1.000000,-1.248075
5,S06,23.000000,78.00,85.0,CS,91.375,4.356709,9.219544,True,False,0.442708,1.664101
6,S07,21.000000,65.00,70.0,IT,71.500,4.174387,8.366600,False,True,0.171875,-0.277350
7,S08,22.000000,81.50,60.0,CS,73.250,4.400603,7.745967,True,False,0.515625,0.693375

In [22]:
filtered = df[df["Marks"] > 70].sort_values("Attendance")
grouped = filtered.groupby("Department")["Marks"].mean()

print(filtered)
print("\nAverage marks by department:\n", grouped)

  Student_ID   Age   Marks  Attendance Department  Marks_MA  Marks_Log  \
7        S08  22.0   81.50        60.0         CS    73.250   4.400603
1        S02  21.0   81.50        75.0         IT    83.250   4.400603
5        S06  23.0   78.00        85.0         CS    91.375   4.356709
4        S05  20.0  104.75        85.0         CS    80.750   4.651577
0        S01  20.0   85.00        90.0         CS    85.000   4.442651
2        S03  22.0   92.00        95.0         CS    86.750   4.521789

   Attendance_Sqrt  Gender_Female  Gender_Male  Marks_MinMax     Age_Z
7         7.745967           True        False      0.515625  0.693375
1         8.660254           True        False      0.515625 -0.277350
5         9.219544           True        False      0.442708  1.664101
4         9.219544          False         True      1.000000 -1.248075
0         9.486833          False         True      0.588542 -1.248075
2         9.746794          False         True      0.734375  0.693375

Average marks by department:
 Department
CS    88.25
IT    81.50
Name: Marks, dtype: float64

In [30]:
df.rename(columns={"Attendance": "Attendance_Percentage"}, inplace=True)
df.drop(columns=["Student_ID"], inplace=True)
df

         Age  Marks  Attendance_Percentage  Gender Department
0  20.000000   85.0                   90.0    Male         CS
1  21.000000   81.5                   75.0  Female         IT
2  22.000000   92.0                   95.0    Male         CS
3  21.285714   45.0                   40.0  Female         IT
4  20.000000  300.0                   85.0    Male         CS
5  23.000000   78.0                   85.0  Female         CS
6  21.000000   65.0                   70.0    Male         IT
7  22.000000   81.5                   60.0  Female         CS

In [31]:
print("Cleaned Dataset\n")
df

Cleaned Dataset

         Age  Marks  Attendance_Percentage  Gender Department
0  20.000000   85.0                   90.0    Male         CS
1  21.000000   81.5                   75.0  Female         IT
2  22.000000   92.0                   95.0    Male         CS
3  21.285714   45.0                   40.0  Female         IT
4  20.000000  300.0                   85.0    Male         CS
5  23.000000   78.0                   85.0  Female         CS
6  21.000000   65.0                   70.0    Male         IT
7  22.000000   81.5                   60.0  Female         CS