In [1]:
import pandas as pd

In [53]:
# Creating the dataframe
data = {
    "Population(in Million)": [331,67,138,126],
    "Capital": ["Washington, D.C.", "Paris", "New Delhi", "Tokyo"]
}
df = pd.DataFrame(data, index=["United States", "France", "India", "Japan"])

In [54]:
df

               Population(in Million)           Capital
United States                     331  Washington, D.C.
France                             67             Paris
India                             138         New Delhi
Japan                             126             Tokyo

In [55]:
# 1. Display the first few rows
print("First few rows of the DataFrame:")
df.head()

First few rows of the DataFrame:

               Population(in Million)           Capital
United States                     331  Washington, D.C.
France                             67             Paris
India                             138         New Delhi
Japan                             126             Tokyo

In [56]:
print("Information about dataframe")
df.info()

Information about dataframe
<class 'pandas.DataFrame'>
Index: 4 entries, United States to Japan
Data columns (total 2 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Population(in Million)  4 non-null      int64
 1   Capital                 4 non-null      str
dtypes: int64(1), str(1)
memory usage: 96.0+ bytes

In [57]:
df.loc['India','Population(in Million)']

np.int64(138)

In [58]:
df[df['Population(in Million)']>100]

               Population(in Million)           Capital
United States                     331  Washington, D.C.
India                             138         New Delhi
Japan                             126             Tokyo

In [59]:
df['GDP']=[23.3,3.7,10,14.6]
df

               Population(in Million)           Capital   GDP
United States                     331  Washington, D.C.  23.3
France                             67             Paris   3.7
India                             138         New Delhi  10.0
Japan                             126             Tokyo  14.6

In [60]:
df = df.rename(columns={"Population(in Million)": "Population_Million"})
df

               Population_Million           Capital   GDP
United States                 331  Washington, D.C.  23.3
France                         67             Paris   3.7
India                         138         New Delhi  10.0
Japan                         126             Tokyo  14.6

In [61]:
df = df.drop(columns=["Capital"])
df

               Population_Million   GDP
United States                 331  23.3
France                         67   3.7
India                         138  10.0
Japan                         126  14.6

In [62]:
df.sort_values(by="Population_Million")

               Population_Million   GDP
France                         67   3.7
Japan                         126  14.6
India                         138  10.0
United States                 331  23.3

In [64]:
df['Population_Million'].mean()

np.float64(165.5)

 # Create a dataset of your class 
a) Find the best student on basis of marks.
b) Find maximum marks in data analytics and print the name of student.
c) Replace the null value with mean.
d) Find the average of your class in DAA.
e) Print first five rows of your dataset.
f) Print last 5 columns of the dataset.

In [76]:
import pandas as pd
import numpy as np
data = {
    "Roll_No" : [1,19,7,4,69,73,35,49,55,52],
    "Name": ["Aadya", "Aditi", "Ayushi", "Aastha", "Anshika", "Anushka", "Ananya", "Akshita", "Anjil", "Amrita"],
    "DAA": [85, 92, 74, 90, 88, 95, 79, 84, 91, 87],
    "D_A": [78, 95, 82, 90,np.nan, 87, 76, 89, 94, 88],
    "ML": [89, 94, 88, 90, 84, 92, 80, 86, 93, 85],
    "PE": [82, 90, 79, 88, 91,np.nan, 77, 85, 92, 89],
    "CN": [84, 91, 76, 89, 93, 96, 78, 87, 95, 90]
}

In [77]:
st_df=pd.DataFrame(data)
st_df

   Roll_No     Name  DAA   D_A  ML    PE  CN
0        1    Aadya   85  78.0  89  82.0  84
1       19    Aditi   92  95.0  94  90.0  91
2        7   Ayushi   74  82.0  88  79.0  76
3        4   Aastha   90  90.0  90  88.0  89
4       69  Anshika   88   NaN  84  91.0  93
5       73  Anushka   95  87.0  92   NaN  96
6       35   Ananya   79  76.0  80  77.0  78
7       49  Akshita   84  89.0  86  85.0  87
8       55    Anjil   91  94.0  93  92.0  95
9       52   Amrita   87  88.0  85  89.0  90

In [79]:
st_df.columns

Index(['Roll_No', 'Name', 'DAA', 'D_A', 'ML', 'PE', 'CN'], dtype='str')

In [116]:
# (c) Replace null values with mean
st_df['D_A'] = st_df['D_A'].fillna(st_df['D_A'].mean())
st_df['PE'] = st_df['PE'].fillna(st_df['PE'].mean())
st_df.head()

   Roll_No     Name  DAA        D_A  ML    PE  CN       Total
0        1    Aadya   85  78.000000  89  82.0  84  418.000000
1       19    Aditi   92  95.000000  94  90.0  91  462.000000
2        7   Ayushi   74  82.000000  88  79.0  76  399.000000
3        4   Aastha   90  90.000000  90  88.0  89  447.000000
4       69  Anshika   88  86.555556  84  91.0  93  442.555556

In [117]:
# (d) Find average marks in DAA
daa_mean=st_df["DAA"].mean()
daa_mean

np.float64(86.5)

In [115]:
st_df["Total"] = st_df[['DAA', 'D_A', 'ML', 'PE', 'CN']].sum(axis=1)
st_df.head()

   Roll_No     Name  DAA        D_A  ML    PE  CN       Total
0        1    Aadya   85  78.000000  89  82.0  84  418.000000
1       19    Aditi   92  95.000000  94  90.0  91  462.000000
2        7   Ayushi   74  82.000000  88  79.0  76  399.000000
3        4   Aastha   90  90.000000  90  88.0  89  447.000000
4       69  Anshika   88  86.555556  84  91.0  93  442.555556

In [113]:
# (a) Find the best student on basis of total marks
best_student = st_df.loc[st_df["Total"].idxmax(), "Name"]
best_student

'Anjil'

In [114]:
# (b) Find maximum marks in Data Analytics and print student name
max_da = st_df["D_A"].max()
student_da = st_df.loc[st_df["D_A"].idxmax(), "Name"]
max_da, student_da

(np.float64(95.0), 'Aditi')

In [100]:
# (e) Print first 5 rows
st_df.head()

   Roll_No     Name  DAA        D_A  ML    PE  CN       Total
0        1    Aadya   85  78.000000  89  82.0  84  418.000000
1       19    Aditi   92  95.000000  94  90.0  91  462.000000
2        7   Ayushi   74  82.000000  88  79.0  76  399.000000
3        4   Aastha   90  90.000000  90  88.0  89  447.000000
4       69  Anshika   88  86.555556  84  91.0  93  442.555556

In [111]:
# (f) Print last 5 columns 
st_df.tail()

   Roll_No     Name  DAA   D_A  ML         PE  CN       Total
5       73  Anushka   95  87.0  92  85.888889  96  455.888889
6       35   Ananya   79  76.0  80  77.000000  78  390.000000
7       49  Akshita   84  89.0  86  85.000000  87  431.000000
8       55    Anjil   91  94.0  93  92.000000  95  465.000000
9       52   Amrita   87  88.0  85  89.000000  90  439.000000